### ISSUE TITLE
Can not compile Ubuntu version.

### ISSUE THREAD

**Issue by jamesaspinwall** [urbint/rox#10]
I get the following:
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

==> rox
Compiling NIF crate :rox_nif (native/rox_nif)...
   Compiling erlang_nif-sys v0.6.2
   Compiling rayon-core v1.2.1
   Compiling coco v0.1.1
   Compiling unreachable v0.1.1
   Compiling syn v0.11.11
error: failed to run custom build command for `erlang_nif-sys v0.6.2`
process didn't exit successfully: `/home/jaspinwall/phx/simplews/_build/dev/rustler_crates/rox_nif/release/build/erlang_nif-sys-f8826d885a6d0b8b/build-script-build` (exit code: 101)
--- stdout
Unsupported Erlang version.

Is the erlang_nif-sys version up to date in the Cargo.toml?
Does 'cargo update' fix it?
If not please report at https://github.com/goertzenator/erlang_nif-sys.

--- stderr
thread 'main' panicked at 'gen_api.erl encountered an error.', /home/jaspinwall/.cargo/registry/src/github.com-1ecc6299db9ec823/erlang_nif-sys-0.6.2/build.rs:28:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
could not compile dependency :rox, "mix compile" failed. You can recompile this dependency with "mix deps.compile rox", update it with "mix deps.update rox" or clean it with "mix deps.clean rox"
** (RuntimeError) Rust NIF compile error (rustc exit code 101)
    lib/mix/tasks/compile.rustler.ex:60: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/tasks/compile.rustler.ex:14: Mix.Tasks.Compile.Rustler.run/1
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:63: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:47: Mix.Tasks.Compile.All.do_compile/4
    (mix) lib/mix/tasks/compile.all.ex:18: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:34: Mix.Tasks.Compile.All.with_logger_app/1

**Comment by rschmukler** [comment]
Closed by #11
