### ISSUE TITLE
Any chance of updating this to work on OTP 21.0?

### ISSUE THREAD

**Issue by walkr** [urbint/rox#14]
Hello,

Is there any chance this will updated to work with Erlang/OTP 21.0, as it just came out?

Thanks!

**Comment by walkr** [comment]
OTP 21.0 support added  in [PR#15](https://github.com/urbint/rox/pull/15)

**Comment by ayrat555** [comment]
@walkr  I think we should reopen it. Because the issue is not resolved

**Comment by walkr** [comment]
@ayrat555 Well, I closed it since no one responded. But I guess it could stay open.
